name: Grid Test Site 1
favicon: null
layout_spectrum: 0.38562
typography_spectrum: 0.6581480093300343
title: Grid Test Site 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070302'
    - '#8c897a'
    - '#00c5ff'
    - '#d8dfe5'
    - '#005cff'
  brandStrength: 0.375
  lightness: 0.7091090970207006
  saturation: 0.278014930896461
  rhythmicContrast: 0.5328892776742578
purpose: []
