name: Grid Test Site 1
favicon: null
layout_spectrum: 0.07595887617208064
typography_spectrum: 0.6581480093300343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3227807115763426
  lightness: 0.7091090970207006
  saturation: 0.278014930896461
  rhythmicContrast: 0.5328892776742578
purpose: []
